### ISSUE TITLE
[HC] Heads up! There may be a problem with your connection to Square. In order to continue accepting payments, please disconnect and re-connect your site.

### ISSUE THREAD

**Issue by OmarFPG** [woocommerce/woocommerce-square#93]
### Describe the bug
Users are getting a warning about disconnecting and reconnecting their site. Trying to do so doesn't fix the problem.

### Expected behavior
The connection should be refreshed automatically every week with the wc_square_refresh_connection action, or a manual reconnect should also work, but neither seem to be working.

### Additional details
Possible workaround by removing the Square connection on the Square side and reinstalling the plugin on WordPress and reconnecting everything on both ends from scratch, as mentioned [here](https://wordpress.org/support/topic/please-disconnect-and-re-connect-your-site/#post-17552789).

Possible related issue: https://github.com/woocommerce/woocommerce-square/issues/92

###
Reports:
- 7971893-zd
- 7979682-zd
- 7978477-zd
- 7994158-zd
- 7995136-zd

#hc

**Comment by shaunkuschel** [comment]
Another report on 8000547-zen.

In this case, the merchant was experiencing issues with the credit card fields not loading. They disconnected and re-connected Square and that fixed the CC field issue but the notice was still being shown in the WordPress admin dashboard. They placed a test order using Square as the gateway and it was successful. However, the admin notification with the `Heads up! There may be a problem with your connection to Square. In order to continue accepting payments, please disconnect and re-connect your site.` message was still being shown and unable to be dismissed/closed.

Screenshot of the admin notification:

![Markup 2024-04-05 at 18 31 11](https://github.com/woocommerce/woocommerce-square/assets/10855013/9b4946be-8bcf-4537-a8fb-aadbcea4b3a1)

**Comment by kaushikasomaiya** [comment]
Potentially affected 8007390-zen

**Comment by OmarFPG** [comment]
8010065-zen

Edit: they've tried the workaround of removing the Square connection and setting up everything again, two tests orders went fine after this (even though the error message is still there).

**Comment by carolframen** [comment]
Another case 8018268-zen

**Comment by carolframen** [comment]
8017913-zen

**Comment by carolframen** [comment]
8018317-zen

**Comment by shameemreza** [comment]
Another report here: 8020654-zen
Thread: https://wordpress.org/support/topic/heads-up-8/

Note: Sync is working!

**Comment by orlovak** [comment]
We’re encountering same issue: Heads up! It appears there’s an issue with your connection to Square. To keep accepting payments, please disconnect and reconnect. However, despite multiple attempts to reconnect, the problem persists. Additionally, we’re unable to access the product data editing feature on our Woocommerce website. Editing images, descriptions, shipping details, attributes—none of the tabs are responsive. This seems to be directly related to the Square plugin, as everything functions properly when disconnected. The synchronization between WooCommerce and Square is functioning as expected. It’s worth noting that we’re using Elementor as well.

status report:
https://quickforget.com/s/d4e2eb1a01ecc9c13c25f290e4f3000556bfb75a9608938a

**Comment by cardehngeh** [comment]
8021481 - zen

**Comment by kgeorgee** [comment]
7971893-zen

**Comment by kgeorgee** [comment]
7974846-zen
8003596-zen

**Comment by vikrampm1** [comment]
This is now resolved with [4.6.1 ](https://github.com/woocommerce/woocommerce-square/releases/tag/4.6.1)release.
